---
title: "Validation"
output: html_document
date: "2024-11-28"
---
```{r}
library(oligo)
library(affycoretools)
```

```{r}
my_id <- "GSE51808"

gse.1 <- getGEO(my_id)[[1]]
pdata.1 <- pData(gse.1)

gsm.1 <- pdata.1 %>% filter(!`status:ch1` == "convalescent")
gsm.1 <- filter(gsm.1, !geo_accession %in% c("GSM1253033", #Amostra removida pelo arrayQualityMetrics
                                          "GSM1253032","GSM1253046")) #Amostras removidas por clusterização
dim(gsm.1)
dir.create(paste0("Samples/", my_id))
for(i in gsm.1$geo_accession){
  getGEOSuppFiles(i, makeDirectory = F, baseDir = paste0("Samples/", my_id))
}

gsm.1$celfile <- str_split(gsm.1$supplementary_file, "/") %>% map_chr(tail,1)
gse.1_celdata <- read.celfiles(paste0("Samples/", my_id,"/", gsm.1$celfile))
#Loading required package: pd.ht.hg.u133.plus.pm
gse.1_celdata@annotation

colnames(eset) == gsm.1$celfile

eset <- rma(gse.1_celdata)
dim(eset)
oligo::hist(eset)

#BiocManager::install("hthgu133pluspm.db")
library(hthgu133pluspm.db)
eset <- annotateEset(eset, hthgu133pluspm.db,
                     columns=c("PROBEID", "ENTREZID","ENSEMBL", "SYMBOL", "GENENAME"))
dim(eset)
fData(eset) %>% View()

eset <- subset(eset, !is.na(fData(eset)$ENSEMBL))
eset <- subset(eset, !grepl("pseudogene", fData(eset)$GENENAME))
eset <- subset(eset, !grepl("LINC", fData(eset)$SYMBOL))

#arrayQualityMetrics::arrayQualityMetrics(eset, force=T)
#Detectado como outlier: "GSM1253033_1444BP0008_81910_H05.CEL.gz"

```
#Baixas leituras
```{r}
medians <- rowMedians(exprs(eset))

hist(medians, 100, freq=F)
abline(v=3.5,col='red')

table(gsm.1$`status:ch1`)

threshold <- apply(eset, 1, function(x) {
  sum(x > 3.5) >= 9
})

table(threshold)
eset <- subset(eset, threshold)
exp.eset <- exprs(eset)
colnames(exp.eset) <- gsm.1$description
```

```{r}
dist <- dist(t(exp.eset))
hc <- hclust(dist)
dend <- as.dendrogram(hc)
dend %>% 
  color_labels(labels = colnames(exp.eset[,which(gsm.1$`status:ch1` == unique(gsm.1$`status:ch1`)[1])]), col='deepskyblue3') %>% 
  color_labels(labels = colnames(exp.eset[,which(gsm.1$`status:ch1` == unique(gsm.1$`status:ch1`)[2])]), col='firebrick1') %>% 
  color_labels(labels = colnames(exp.eset[,which(gsm.1$`status:ch1` == unique(gsm.1$`status:ch1`)[3])]), col='orange') %>% 
  plot()
legend('topright',
       legend=c(unique(gsm.1$`status:ch1`)),
       col=c('deepskyblue', 'firebrick1', 'orange'),
       pch=c(20,20,20))

pca.1 <- PCA(t(exp.eset), graph=F)
fviz_pca_ind(pca.1,
             mean.point=F,
             geom.ind = c('point', 'text'), pointshape=21,
             fill.ind = gsm.1$`status:ch1`,
             addEllipses = T, ellypse.type="confidence")+
  scale_fill_manual(values=c("deepskyblue3", "firebrick1", "orange"))+
  scale_color_manual(values=c("deepskyblue3", "firebrick1", "orange"))+
  theme_classic()+
  theme(legend.title = element_blank(),
        title = element_blank())
```

#DEG
```{r}
gsm.1$`status:ch1`

design.1 <- model.matrix(~0 + gsm.1$`status:ch1`)
colnames(design.1) <- c("Control", "DF", "DHF")

contrastsMatrix <- makeContrasts(DF - Control,
                                 DHF - Control,
                                 DF - DHF,
                                 levels=colnames(design.1))

fit <- lmFit(eset, design.1)
fit <- contrasts.fit(fit, contrasts = contrastsMatrix)
fit2 <- eBayes(fit)

summary(decideTests(fit, lfc=2, adjust.method = "fdr", p.value = 0.05))
res.df <- topTable(fit2, number=Inf, coef = 1)
res.dhf <- topTable(fit2, number=Inf, coef = 2)

#Adicionar o logFC aos dataframes com os alvos e miRs exclusivos
#exc.prot: exclusive protector targets
#exp.pred: exclusive preditive targets

res.df <- res.df %>% dplyr::arrange(dplyr::desc(abs(logFC))) %>% distinct(., SYMBOL, .keep_all = T)
res.dhf <- res.dhf %>% dplyr::arrange(dplyr::desc(abs(logFC))) %>% distinct(., SYMBOL, .keep_all = T)
```

#Targets
```{r}
exc.prot_df <- exc.prot %>% left_join(res.df[,c("SYMBOL", "logFC", "P.Value", "adj.P.Val")], by=c("hgnc_symbol" = "SYMBOL")) %>% dplyr::rename("logFC_miR" = "logFC.x", "logFC_DF" = "logFC.y") %>% na.omit()

exc.pred_dhf <-  exc.pred %>% left_join(res.dhf[,c("SYMBOL", "logFC", "P.Value", "adj.P.Val")], by=c("hgnc_symbol" = "SYMBOL")) %>% dplyr::rename("logFC_miR" = "logFC.x", "logFC_DHF" = "logFC.y") %>% na.omit()

#DEGs dos miR preditores:
exc.pred_dhf <- exc.pred_dhf %>% filter(adj.P.Val<0.05, abs(logFC_DHF) > 1)

#DEGs dos miR protetores:
exc.prot_df <- exc.prot_df %>% filter(adj.P.Val<0.05, abs(logFC_DF) > 1)
```

```{r}
#Heatmap da expressao dos genes selecionados
##Transformar o eset.1 para ter os simbolos de genes no lugar das probes do array
exp.genes <- exp.eset %>% as.data.frame() %>% rownames_to_column(., var="PROBEID") %>% 
  left_join(., fData(eset)[,c(1,4)])

exp.genes <- exp.genes %>% filter(SYMBOL %in% unique(rbind(exc.pred_dhf, exc.prot_df)$hgnc_symbol))
#exp.genes <- exp.genes %>% filter(SYMBOL %in% unique(exc.pred_dhf$hgnc_symbol))

exp.genes$PROBEID <- NULL
#media da expressao para genes com probes repetidas:
exp.genes <- exp.genes %>% 
  group_by(SYMBOL) %>% 
  summarise(across(everything(), mean))

exp.genes <- exp.genes %>% column_to_rownames(., "SYMBOL")

#Df para anotação dos genes na lateral do heatmap
genes_ann <- data.frame(Genes=unique(rbind(exc.pred_dhf, exc.prot_df)$hgnc_symbol))
genes_ann <- genes_ann %>% mutate(Reg = ifelse(Genes %in% exc.prot_df$hgnc_symbol, "Prot", "Pred")) %>% column_to_rownames(., var="Genes")
amostras_ann <- data.frame(amostras=gsm.1$description, grupo = gsm.1$`status:ch1`)
amostras_ann <- amostras_ann %>% column_to_rownames(., "amostras")

pheatmap(exp.genes,
  #exp.genes[,!grepl("c.*",colnames(exp.genes))],
         scale="row",
         border_color = NA,
         cluster_rows = T,
         cluster_cols = T, 
         treeheight_row = 0, show_colnames = F,
         color=colorRampPalette(c("darkblue", "deepskyblue3", "white", "firebrick1", "firebrick3"))(200), fontsize_row = 6,
         annotation_col = amostras_ann, annotation_row = genes_ann, annotation_colors = list(Reg = c("Prot" = "purple3", "Pred" = "green"),
                                                                                                                        grupo = c("DF" = "firebrick1", "DHF" = "gold2", "control"="grey")))
```

#Enrichment
```{r}
library(clusterProfiler)

#Adicionar identificadores de genes aos resultados
exc.pred_dhf <- exc.pred_dhf %>% left_join(fData(eset)[,c(2,3,4)], by = c("hgnc_symbol" = "SYMBOL"))

exc.prot_df <- exc.prot_df %>% left_join(fData(eset)[,c(2,3,4)], by = c("hgnc_symbol" = "SYMBOL"))
```

```{r}
wp.prot <- enrichWP(gene = exc.prot_df$ENTREZID, organism = "Homo sapiens")
wp.prot@result %>% View()
#
wp.pred <- enrichWP(gene = exc.pred_dhf$ENTREZID, organism = "Homo sapiens")
wp.pred@result %>% View()
##--
kg.prot <- enrichKEGG(gene=exc.prot_df$ENTREZID, organism = "hsa")
kg.prot@result %>% View()
#
kg.pred <- enrichKEGG(gene=exc.pred_dhf$ENTREZID, organism = "hsa")
kg.pred@result %>% View()
##--
rc.prot <- ReactomePA::enrichPathway(gene=exc.prot_df$ENTREZID, pvalueCutoff = .05)
rc.prot@result %>% View()
#
rc.pred <- ReactomePA::enrichPathway(gene=exc.pred_dhf$ENTREZID, pvalueCutoff = .05)
rc.pred@result %>% View()
##--
go.prot <- enrichGO(gene=exc.prot_df$ENTREZID, ont = "BP", OrgDb = org.Hs.eg.db)
go.prot@result %>% View()
#
go.pred <- enrichGO(gene=exc.pred_dhf$ENTREZID, ont = "BP", OrgDb = org.Hs.eg.db)
go.pred@result %>% View()
```

